language: scala

sudo: required

dist: precise

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/spark
    - $HOME/.cache/pip
    - $HOME/.pip-cache
    - $HOME/.sbt/launchers

jdk:
  - oraclejdk8

scala:
   - 2.11.8

sudo: false

addons:
  apt:
    packages:
      - axel

before_install:
  - export PATH=$HOME/.local/bin:$PATH
  - pip install --user codecov coverage

install:
  # Download spark 2.2.2
  - "[ -f spark ] || mkdir spark && cd spark && axel http://www-us.apache.org/dist/spark/spark-2.3.1/spark-2.3.1-bin-hadoop2.7.tgz && cd .."
  - "tar -xf ./spark/spark-2.3.1-bin-hadoop2.7.tgz"
  - "export SPARK_HOME=`pwd`/spark-2.3.1-bin-hadoop2.7"
  - echo "spark.yarn.jars=$SPARK_HOME/jars/*.jar" > $SPARK_HOME/conf/spark-defaults.conf
  # Install Python deps.
  # The conda installation steps here are based on http://conda.pydata.org/docs/travis.html
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - deps='pip coverage py4j'
  - conda create -p $HOME/py --yes $deps "python=3.6"
  - export PATH=$HOME/py/bin:$SPARK_HOME/bin:$SPARK_HOME/sbin:$PATH
  - pip install --upgrade codecov

script:
  - export S3DHOME="/home/travis/build/astrolabsoftware/spark3D"
  - export SCALA_BINARY_VERSION="2.11.8"
  - export PYTHONPATH="$SPARK_HOME/python:$S3DHOME:$S3DHOME/pyspark3d:$PYTHONPATH"
  - ./test_scala.sh $SCALA_BINARY_VERSION
  - bash <(curl -s https://codecov.io/bash) -cF scala
  - ./test_python.sh $SCALA_BINARY_VERSION
  - bash <(curl -s https://codecov.io/bash) -cF python
